HISTFILE=$HOME/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000

zstyle ':completion:*' menu select
zstyle ':completion:*' completer _complete
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+l:|=* r:|=*'

unsetopt menu_complete
unsetopt flowcontrol

setopt prompt_subst
setopt always_to_end
setopt append_history
setopt auto_menu
setopt complete_in_word
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt interactivecomments
setopt share_history

eval $(starship init zsh)

if [ -f "/usr/share/zsh-plugins/autosuggestions/autosuggestions.zsh" ]; then
    source /usr/share/zsh-plugins/autosuggestions/autosuggestions.zsh
fi

if [ -f "/usr/share/zsh-plugins/syntax-highlighting/plugin.zsh" ]; then
    source /usr/share/zsh-plugins/syntax-highlighting/plugin.zsh
fi
